name: Headless Tests

on:
  workflow_dispatch:

jobs:
  headless-chrome:
    runs-on: ubuntu-latest
    container: selenium/standalone-chrome
    steps:
      - uses: actions/checkout@v1
      - name: install node
        run: |
          sudo apt-get update
          sudo apt-get -y install nodejs
      - name: build
        run: npm run ci-build

      - name: run tests
        run: node ./tools/jil/bin/cli.js -f merged -b chrome@latest/linux -t 85000 --no-retry --selenium-server=localhost:4444
