name: Headless Tests

on:
  workflow_dispatch:

jobs:
  headless-chrome:
    runs-on: ubuntu-latest
    container: circleci/node:12-browsers
    steps:
      - uses: actions/checkout@v1
      - name: permissions
        run: sudo chmod -R 777 /github /__w
      - name: build
        run: npm run ci-build

      - name: run tests
        run: node ./tools/jil/bin/cli.js -f merged -b chrome@latest/linux -t 85000 --no-retry --unit-only
