name: Build and publish release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag appended to version number'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v2
      - name: setup build folder
        run: |
          mkdir build
          echo $(cat VERSION)-${{ github.event.inputs.tag }} > build/build_number
          echo $GITHUB_SHA > build/git_commit
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./.npm
          key: ${{ runner.os }}-publish-${{ hashFiles('**/package-lock.json') }}
      - name: build
        run: npm run ci-build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  publish-to-s3:
    needs: build
    runs-on: ubuntu-latest
    container: node:14
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./.npm
          key: ${{ runner.os }}-publish-${{ hashFiles('**/package-lock.json') }}
      - name: install
        run: npm ci
      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: upload artifacts to S3
        run: |
          node tools/scripts/upload-to-s3.js \
            --bucket ${{ secrets.AWS_BUCKET }} \
            --role ${{ secrets.AWS_ROLE_ARN }}
  publish-to-nr:
    needs: build
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./.npm
          key: ${{ runner.os }}-publish-${{ hashFiles('**/package-lock.json') }}
      - name: install
        run: npm ci
      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: upload artifacts to NR
        run: |
          node tools/scripts/upload-to-nr.js \
            --staging-api-key=${{ secrets.NR_API_KEY_STAGING }} \
            --production-api-key=${{ secrets.NR_API_KEY_PRODUCTION }} \
            --eu-api-key=${{ secrets.NR_API_KEY_EU }}
